### ISSUE TITLE
Error generating TXT report: [Errno 36] File name too long:

### ISSUE THREAD

**Issue by brother0k** [jasonxtn/Argus#10]
When use: 53. Run All Infrastructure Tools

`Error generating TXT report: [Errno 36] File name too long: '/home/user/tools/argus/results/example.com_Associated Hosts_DNS Over HTTPS_DNS Records_DNSSEC Check_Domain Info_Domain Reputation Check_IP Info_Open Ports Scan_Server Info_Server Location_SSL Chain Analysis_SSL Expiry Alert_TLS Cipher Suites_TLS Handshake Simulation_Traceroute_TXT Records_WHOIS Lookup_Zone Transfer.txt'`

**Comment by jasonxtn** [comment]
Sir it's duplicate issue, i will close this and leave the other one till i fix it.

**Comment by brother0k** [comment]
Ah ok. Thanks
