### ISSUE TITLE
Error generating TXT report: [Errno 36] File name too long:

### ISSUE THREAD

**Issue by brother0k** [jasonxtn/Argus#11]
When use: 54. Run All Web Intelligence Tools
`Error generating TXT report: [Errno 36] File name too long: '/home/user/tools/argus/results/example.com_Archive History_Broken Links Detection_Carbon Footprint_CMS Detection_Cookies Analyzer_Content Discovery_Crawler_Robots.txt Analyzer_Directory Finder_Performance Monitoring_Quality Metrics_Redirect Chain_Sitemap Parsing_Social Media Presence Scan_Technology Stack Detection_Third-Party Integrations.txt'`

**Comment by jasonxtn** [comment]
Problem solved. Updated to the latest version.
