### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.report_generator'

### ISSUE THREAD

**Issue by kernelshock** [jasonxtn/Argus#18]
It looks like this module is deprecated, or missing, python can't import it.
There exist any fix to this?
Thank you very much!!!

**Comment by RP5406** [comment]
I ran into the same issue, I had tried many times in one instance of Kali and couldn't get it to work. However, I tried it on another kali vm I have and it worked, no issues. I didn't do a comparison but if you happen to have a different vm to try it on, go for it.

**Comment by jasonxtn** [comment]
Sorry for the late answer,

The tool is working fine try those steps :

- Clone the latest version of the project.
- Run it from the terminal ( do not double click or whatever)
- Update to the latest version of python
- Check your Python environment
PYTHONPATH: If the error persists, you can add the project directory to your PYTHONPATH:
export PYTHONPATH=$PYTHONPATH:/path/to/argus
- Try using python3 argus.py
