### ISSUE TITLE
Other unix os support?

### ISSUE THREAD

**Issue by hexdrx** [jasonxtn/Argus#20]
Is it available on Manjaro or Mac? Or it only can be deployed only on Kali?

**Comment by jasonxtn** [comment]
It is compatible with Windows, all Linux distributions, and Unix. While I haven't tested it on macOS, I believe it will work as well. Just make sure you have the latest version of Python installed

**Comment by opticaldrive** [comment]
I’ll test it on macOS later today, and report issues of anything doesn’t work.
Update: Works great!

**Comment by nevermore23274** [comment]
It's python based, not OS based. I have it running out of a container with Ubuntu, but made a container with specifically Kali awhile back [in this closed issue](https://github.com/jasonxtn/Argus/issues/17#issuecomment-2405164463).

**Comment by opticaldrive** [comment]
Recommend this to be closed, perhaps as not planned.
