### ISSUE TITLE
39. Data Leak Detection  always returns example breaches?

### ISSUE THREAD

**Issue by opticaldrive** [jasonxtn/Argus#21]
Hello, awesome project,
Command 39. Data Leak Detection  always returns example breaches?
I always get a bunch of tables with the name ExampleBreach, am I lacking a API key?
Is this intended?
Thank you very much.

**Comment by jasonxtn** [comment]
Sorry sir i forgot to update it it's not complete, I will update it soon.

**Comment by opticaldrive** [comment]
Got it, thanks.
