### ISSUE TITLE
Google API Key

### ISSUE THREAD

**Issue by iaintshootinmis** [jasonxtn/Argus#3]
First off, awesome awesome work. 
Second, would love to contribute and see if I can fix little things as I run across them. 

Third, for documentations sake, what in the world is the "Google API Key"? 
There are currently [469](https://console.cloud.google.com/apis/library) API types in the Google API library. 
And despite my best efforts, I haven't determined which one works.

Thanks, again awesome. Can't wait to train our analysts on this. <3

**Comment by jasonxtn** [comment]
Hi
Thank you sir.
it's Google Cloud Console API ( Don't forgot to Enable the PageSpeed Insights API)

**Comment by jasonxtn** [comment]
Hi
Thank you sir.
it's PageSpeed Insights API  (Google Cloud Console API)

**Comment by nevermore23274** [comment]
> First off, awesome awesome work. Second, would love to contribute and see if I can fix little things as I run across them.
> 
> Third, for documentations sake, what in the world is the "Google API Key"? There are currently [469](https://console.cloud.google.com/apis/library) API types in the Google API library. And despite my best efforts, I haven't determined which one works.
> 
> Thanks, again awesome. Can't wait to train our analysts on this. <3

Line 13 of the [settings.py](https://github.com/jasonxtn/Argus/blob/main/config/settings.py) is:

`"GOOGLE_API_KEY": "YOUR_GOOGLE_PageSpeed_Insights_API_KEY",     # API key for Google`

Doesn't it say in the quotes what it is? PageSpeed_Insights?
