### ISSUE TITLE
Directory bruteforcing 

### ISSUE THREAD

**Issue by iNoSec2** [jasonxtn/Argus#6]
Hi,
First of all i just wanted to thank you for your work, it is great!!!
For directory bruteforcing did you compared it to ffuf? Just to know if you have some stat about speed and efficiency.
Have a good day!!

**Comment by jasonxtn** [comment]
Thank you sir,
There no much big difference both are multi-threaded directory fuzzing tools, but to be honest ffuf is slighly faster (it's written in go which is faster than python also it a tool dedicated to directory fuzzing )
