### ISSUE TITLE
Cybercrime intelligence integration

### ISSUE THREAD

**Issue by hudsonrock-partnerships** [jasonxtn/Argus#9]
Consider adding Hudson Rock's complimentary community data to receive additional intelligence associated with a specific domain. The relevant section in the Argus for this type of data is most likely "Security and Threat Intelligence"

- Compromised employees, users, and third parties information. The data was retrieved from infected computers with the Infostealer malware.
Sample query: https://cavalier.hudsonrock.com/api/json/v2/osint-tools/search-by-domain?domain=tesla.com

- Additional URLs associated with a specific domain. The data was retrieved from infected computers with the Infostealer malware and may contain URLs that usually cannot be found conventionally.
 Sample query: https://cavalier.hudsonrock.com/api/json/v2/osint-tools/urls-by-domain?domain=tesla.com

**Comment by jasonxtn** [comment]
Thank you for the suggestion, 
i will try to add it in the first update.
